// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASQnm_IQzgdrPilhQN2p0xrR0I4HmYRaU',
    appId: '1:455488282428:android:0a8e3de70324d4caf14839',
    messagingSenderId: '455488282428',
    projectId: 'camabelcommunity',
    databaseURL: 'https://camabelcommunity-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camabelcommunity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqgfKC2CAitox8ce_N6IrhaBGed7IeCcQ',
    appId: '1:455488282428:ios:4b0f949593c40491f14839',
    messagingSenderId: '455488282428',
    projectId: 'camabelcommunity',
    databaseURL: 'https://camabelcommunity-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camabelcommunity.firebasestorage.app',
    iosBundleId: 'com.hrajaona.camabelcommunity.camabelcommunity',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-azBHUwCaz0YgJSQ_wCB4WX_pT70l8o',
    appId: '1:455488282428:web:910cbc0a75be21e2f14839',
    messagingSenderId: '455488282428',
    projectId: 'camabelcommunity',
    authDomain: 'camabelcommunity.firebaseapp.com',
    databaseURL: 'https://camabelcommunity-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camabelcommunity.firebasestorage.app',
    measurementId: 'G-9J348TF1LD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqgfKC2CAitox8ce_N6IrhaBGed7IeCcQ',
    appId: '1:455488282428:ios:632c2896a2c05bdff14839',
    messagingSenderId: '455488282428',
    projectId: 'camabelcommunity',
    databaseURL: 'https://camabelcommunity-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camabelcommunity.firebasestorage.app',
    iosBundleId: 'com.hrajaona.camabelcommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1-azBHUwCaz0YgJSQ_wCB4WX_pT70l8o',
    appId: '1:455488282428:web:a6db12294fc8f873f14839',
    messagingSenderId: '455488282428',
    projectId: 'camabelcommunity',
    authDomain: 'camabelcommunity.firebaseapp.com',
    databaseURL: 'https://camabelcommunity-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camabelcommunity.firebasestorage.app',
    measurementId: 'G-Z2WT566GLN',
  );

}